agroshop/agroshop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.admin import shop_admin

urlpatterns = [
    path("", include('shop.urls')),
    path('admin/', admin.site.urls),
    path('shopadmin/', shop_admin.urls),
    path("accounts/", include("allauth.urls")),
]

agroshop/shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.index, name="homepage"),
    path("location", views.locationSearch, name="locationsearch"),
    path("viewproduct/pid=<int:pid>", views.viewProduct, name="viewproduct"),
    path("accounts/profile/", views.profile),

    path("createshop", views.createShop, name="createshop"),
    path("new_shop_setup", views.setupShop, name="setupshop"),
    path("myshop", views.myshop, name="myshop"),
    path("addproduct", views.addproduct, name="addproduct"),
    path("uploadproduct", views.uploadedproduct, name="uploadproduct"),
    path("viewshop/shopid=<int:sid>", views.viewshop, name="viewshop"),
    path("cart", views.addToCart, name="viewcart"),
    path("cart/pid=<int:pid>", views.addToCart, name="addtocart"),
    path("removefromcart/pid=<int:pid>", views.removefromcart, name="removefromcart"),

    
    path("selectaddress/cartid=<int:cartid>", views.selectaddress, name="selectaddressforcart"),
    path("selectaddress/prodid=<int:prodid>", views.selectaddress, name="selectaddressforprod"),

    # path("checkout", views.checkout, name="checkout"),
    path("checkout/pid=<int:pid>", views.checkout, name="checkoutproduct"),
    path("checkout/cartid=<int:cartid>", views.checkout, name="checkoutcart"),
    path("paymentstatus", views.paystatus, name="paystatus"),
    path("paymentstatus/status=<str:status>", views.paymentstatus, name="paymentstatus"),

    path("qrsavedetails", views.qrsavedetails, name="qrsavedetails"),

    path("myorders", views.myorders, name="myorders"),
    path("customize/<int:shopid>", views.customize, name="customize"),
    path("submitcomment", views.submitcomment, name="submitcomment"),
    path("submitrating", views.submitrating, name="submitrating"),
    path("shopsaroundyou", views.shopsAroundYou, name="shopsaroundyou"),
    path("displaymap/shopid=<int:shopid>", views.displaymap, name="displaymap"),
    path("searchforproduct", views.searchforproduct),
    path("search_results", views.search, name='searchsomething'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agroshop/shop/models.py
from django.db import models
from sortedm2m.fields import SortedManyToManyField
from datetime import date, timedelta

d = date.today()

states = (
    ('Not mentioned','Choose a state'),
    ('Andhra Pradesh', 'ANDHRA PRADESH'),
    ('Arunachal Pradesh', 'ARUNACHAL PRADESH'),
    ('Assam', 'ASSAM'),
    ('Bihar', 'BIHAR'),
    ('Chandigarh', 'CHANDIGARH'),
    ('Chhattisgarh', 'CHHATTISGARH'),
    ('Delhi', 'DELHI'),
    ('Goa', 'GOA'),
    ("Gujarat", 'GUJARAT'),
    ('Haryana', 'HARYANA'),
    ('Himachal Pradesh', 'HIMACHAL PRADESH'),
    ('Jammu & Kashmir', 'JAMMU & KASHMIR'),
    ('Jharkhand', 'JHARKHAND'),
    ('Karnataka', 'KARNATAKA'),
    ('Kerala', 'KERALA'),
    ('Madhya Pradesh', 'MADHYA PRADESH'),
    ('Maharastra', 'MAHARASTRA'),
    ('Manipur', 'MANIPUR'),
    ('Meghalaya', 'MEGHALAYA'),
    ('Mizoram', 'MIZORAM'),
    ('Nagaland', 'NAGALAND'),
    ('Odisha','ODISHA'),
    ('Punjab', 'PUNJAB'),
    ('Rajasthan', 'RAJASTHAN'),
    ('Sikkim', 'SIKKIM'),
    ('Tamil nadu', 'TAMIL NADU'),
    ("Telangana", 'TELANGANA'),
    ('Tripura', 'TRIPURA'),
    ('Uttar pradesh', 'UTTAR PRADESH'),
    ('Uttarakhand', 'UTTARAKHAND'),
    ('West bengal', 'WEST BENGAL')
)

addresstypes = (
    ('Home', 'Home'),
    ('Office/Commercial', 'Office/Commercial')
)

# Create your models here.
class ASusers(models.Model):
    username = models.CharField(max_length=80)
    # user picture will be provided by google in form of an URL
    # so we are using charfield to store it
    userpicture = models.CharField(max_length=1000, default="")

    def __str__(self):
        return(f"{self.username}")

class Shop(models.Model):
    owner = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name="usershop")
    shopname = models.CharField(max_length=30)
    passkey = models.CharField(max_length=20)
    verificationStatus = models.BooleanField(default=False)
    shoppicture = models.ImageField(upload_to='shopimages/' ,default='../static/black.png')
    coverpic = models.ImageField(default='../static/default.jpg', blank=True)
    description = models.CharField(max_length=1000 ,default='')
    location = models.CharField(max_length=20, default="")
    latitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    longitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    date_created = models.CharField(max_length=15, default=d)
    portfolio = models.CharField(max_length=500, default='', blank=True)
    fblink = models.CharField(max_length=500, default='', blank=True)
    twitterlink = models.CharField(max_length=500, default='', blank=True)
    instalink = models.CharField(max_length=500, default='', blank=True)
    maplink = models.CharField(max_length=1000, default="", blank=True)

    def __str__(self):
        return(f"{self.shopname}")

class Product(models.Model):
    productname = models.CharField(max_length=40)
    soldby = models.CharField(max_length=20, default="Not Available")
    actualPrice = models.IntegerField()
    discountedPrice = models.IntegerField()
    producttype = models.CharField(max_length=15)
    material = models.CharField(max_length=15)
    quantity = models.IntegerField()
    warranty = models.IntegerField()
    countryoforigin = models.CharField(max_length=15)
    description = models.CharField(max_length=200, default="Not Available")
    uploadedshop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name="products")
    onestar = models.IntegerField(default=0)
    twostar = models.IntegerField(default=0)
    threestar = models.IntegerField(default=0)
    fourstar = models.IntegerField(default=0)
    fivestar = models.IntegerField(default=0)
    image1 = models.ImageField(upload_to="productImages/")
    image2 = models.ImageField(upload_to="productImages/")
    image3 = models.ImageField(upload_to="productImages/", null=True)
    image4 = models.ImageField(upload_to="productImages/", null=True)
    featuredProduct = models.BooleanField(default=False)
    average_rating = models.IntegerField(default=0)

    def __str__(self):
        return(f"id:{self.id} {self.productname}")

class Cart(models.Model):
    cartowner = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name="cartowner")
    products = SortedManyToManyField(Product, blank=True, related_name="productsincart")


class ProductCategory(models.Model):
    productcategoryname = models.CharField(max_length=30)
    owner = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name='categories')
    shopname = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='shopproductcategories', blank=True, null=True)
    productname = SortedManyToManyField(Product, blank=True, related_name='productcategories')

class Address(models.Model):
    address_owner = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name="useraddress")
    fullname = models.CharField(max_length=35)
    mobilenumber = models.CharField(max_length=15)
    pincode = models.CharField(max_length=10)
    house_no = models.CharField(max_length=20)
    area = models.CharField(max_length=30)
    landmark = models.CharField(max_length=40)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20, choices=states)
    country = models.CharField(max_length=10)
    addresstype = models.CharField(max_length=30, choices=addresstypes)

    def __str__(self):
        return (f"{self.fullname}, {self.house_no}, {self.area}, {self.landmark}, {self.city}, {self.state}, {self.country}, {self.pincode}.")

class Orders(models.Model):
    razorpay_orderid = models.CharField(max_length=50, default="undefined")
    transactionid = models.CharField(max_length=50, default="undefined")
    signature = models.CharField(max_length=75, default="undefined")
    orderby = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name="userorders")
    ordered_products = SortedManyToManyField(Product, related_name="orderedproducts", help_text="Note: Reference field only, You won't get extra money for selecting products other than customer selected ones!")
    payment_status = models.BooleanField(default=False)
    delivary_status = models.BooleanField(default=False, help_text="Mark this once order has been delivered.")
    date = models.CharField(max_length=20)
    expecteddate = models.CharField(max_length=20, default="")
    rating = models.IntegerField(default=0)
    shippingAddress = models.ForeignKey(Address, on_delete=models.CASCADE, related_name="useraddress", help_text="Shipping address for reference.")
    orderstatus = models.CharField(max_length=100, default="Order Placed", help_text="Help customer to track orderby entering tracking status.")
    ordertotal = models.IntegerField(default=0)

    def __str__(self):
        return (f"Order ID {self.id}")

class Comment(models.Model):
    commentator = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name="usercomments")
    comment = models.CharField(max_length=500, default='')
    commented_product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="productcomments")
    date = models.CharField(max_length=20)

class Rating(models.Model):
    rated_by = models.ForeignKey(ASusers, on_delete=models.CASCADE, related_name="userratings")
    rating = models.IntegerField(default=0)
    rated_product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="productratings")
    date = models.CharField(max_length=20)

agroshop/shop/forms.py
from django import forms
from .models import Shop, Product, Address
class AddShopForm(forms.ModelForm):
    passkey = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    description = forms.CharField(widget=forms.Textarea, max_length=1000)
    portfolio = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}))
    fblink = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}))
    twitterlink = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}))
    instalink = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    longitude = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    latitude = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    maplink = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter map URL'}))
    class Meta:
        model = Shop
        fields = ['owner', 'shopname', 'shoppicture', 'passkey', 'description', 'location', 'latitude', 'longitude', 'portfolio', 'fblink', 'twitterlink', 'instalink', 'maplink']

class AddProductForm(forms.ModelForm):
    productname = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':'Add a title that describes your product'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Tell viewers about the product'}))
    actualPrice = forms.IntegerField()
    discountedPrice = forms.IntegerField()
    producttype = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':'Mention type of the product'}))
    material = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':'Material used for manufacturing product'}))
    quantity = forms.IntegerField()
    warranty = forms.IntegerField()
    countryoforigin = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':'Country of Manufacturing'}))
    soldby = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':"Product's manufacturer name"}))
    class Meta:
        model = Product
        fields = ['productname',"description", 'soldby', 'actualPrice', 'discountedPrice', 'producttype', 'material', 'quantity', 'warranty','countryoforigin', 'uploadedshop', 'image1', 'image2', 'image3', 'image4', 'featuredProduct']

class AddAddressForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Your Full Name goes here'}))
    mobilenumber = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':"Mobile number"}))
    pincode = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':"6 digits [0-9] PIN code"}))
    house_no = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':""}))
    area = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':""}))
    landmark = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':"E.g. near apollo hospital"}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':""}))
    country = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':""}))

    class Meta:
        model = Address
        fields = ['address_owner', 'fullname', 'mobilenumber', 'pincode', 'house_no', 'area', 'landmark', 'city', 'state', 'country', 'addresstype']

agroshop/shop/templates/shop/addaddress.html
<html lang="en">
    <head>
        <title>Select a delivary address</title>
        <!--Favicon-->
        <link rel="icon" href="../../static/Bag_favicon.jpg" type="image/x-icon">
        <!-- Bootstrap Link -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <!-- font awesome link -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="../../static/style.css">
        <script src="../../static/script.js"></script>

        <!-- JQUERY (First) -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>

        <!-- BOOTSTRAP JS (Last) -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>

        <!-- HANDLE BARS TEMPLATE-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        
        <style>
            label, #adsubmitbtn{
                margin-left: 25px;
            }

            #adsubmitbtn{
                margin-bottom: 30px;
            }

            #selad > p, #selad>a{
                margin-left: 25px;
            }
            #selad{
                margin-bottom: 0px;
            }

            
            

        </style>
        
    </head>

    <body>
        <img src="../../static/Screenshot (86).png" alt="" width="130px" height="55px">

        {% if savedadd%}
            <div id="selad" class="shadow-sm p-3 bg-white rounded">
                <h3>Select delivary address</h3>
                <small style="margin-left: 25px;">Is the address you'd like to use displayed below? If so, click the corresponding "Deliver to this address" button. Or you can <a href="#addnewaddressdiv">enter a new delivery address.</a></small> <br>
                <hr>
                <p style="display: inline-block;">
                    <b>{{savedadd.fullname}}</b> <br>
                    <small>{{savedadd.house_no}}</small> <br> 
                    <small>{{savedadd.area}}</small> <br>
                    <small>{{savedadd.city}}</small> <br>
                    <small>{{savedadd.state}}</small> <br>
                    <small>{{savedadd.pincode}}</small> <br>
                    <small>{{savedadd.country}}</small> <br>
                </p> <br>
                <!-- if used previously saved address directly redirecting to checkout using this button -->
                {% if iscart%}
                    <a href="{% url 'checkoutcart' cartobj.id %}"><button class="btn" type="submit" style="background-color: #f2cc6e;">Use this address</button></a>
                {%else%}
                    <a href="{% url 'checkoutproduct' prodobj.id %}"><button class="btn" type="submit" style="background-color: #f2cc6e;">Use this address</button></a>
                {%endif%}

            </div>
        {%endif%}

        <div id="addnewaddressdiv" class="shadow p-3 mb-5 bg-white rounded">
            <h3 class="">Add a new Address</h3>
            <small>Fill in the below fields to select a new address to which products are to be delivered.</small>
        </div>

        {%if iscart%}
            <form action="{% url 'selectaddressforcart' cartobj.id %}" method="POST" enctype="multipart/form-data">
        {%else%}
            <form action="{% url 'selectaddressforprod' prodobj.id %}" method="POST" enctype="multipart/form-data">
        {%endif%}
            

            {%csrf_token%}
            
            <label for="fullname">Full name</label>
            {{form.fullname}} <br>

            <label for="mobilenumber">Mobile number</label>
            {{form.mobilenumber}}  <br>

            <label for="pincode">Pincode</label>
            {{form.pincode}}  <br>

            <label for="house_no">Flat, House no., Building, Company, Apartment</label>
            {{form.house_no}} <br>

            <label for="area">Area, Street, Sector, Village</label>
            {{form.area}} <br>

            <label for="landmark">Landmark</label>
            {{form.landmark}} <br>

            <label for="city">Town/City</label>
            {{form.city}} <br>

            <label for="state">State</label>
            {{form.state}} <br><br>

            <label for="country">Country</label>
            {{form.country}} <br>

            <label for="addresstype">Address Type</label>
            {{form.addresstype}} 

            {{form.address_owner}}
            <p id="userobjid" tabindex="-1" style="display: inline-block; color: #ffffff;">{{userobj.id}}</p> <br><br>

            <button id="adsubmitbtn" class="btn" type="submit" style="background-color: #f2cc6e;">Use this address</button>
        </form>
        <hr style="width: 80%;">


        <div style="text-align: center;">
            <small><a href="">Privacy Notice</a> &copy; 2012-2022, AgroShop.com</small>
            <br>
            <br>
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', ()=>{
                document.querySelector('#id_fullname').style.width = "300px";
                document.querySelector('#id_fullname').style.marginLeft = "25px";

                document.querySelector('#id_mobilenumber').style.width = "300px";
                document.querySelector('#id_mobilenumber').style.marginLeft = "25px";

                document.querySelector('#id_pincode').style.width = "300px";
                document.querySelector('#id_pincode').style.marginLeft = "25px";

                document.querySelector('#id_house_no').style.width = "300px";
                document.querySelector('#id_house_no').style.marginLeft = "25px";

                document.querySelector('#id_area').style.width = "300px";
                document.querySelector('#id_area').style.marginLeft = "25px";

                document.querySelector('#id_landmark').style.width = "300px";
                document.querySelector('#id_landmark').style.marginLeft = "25px";

                document.querySelector('#id_city').style.width = "300px";
                document.querySelector('#id_city').style.marginLeft = "25px";

                document.querySelector('#id_country').style.width = "300px";
                document.querySelector('#id_country').style.marginLeft = "25px";

                const user_obj_id = document.querySelector('#userobjid').innerHTML;
                document.querySelector('#id_address_owner').value = user_obj_id;
                document.querySelector('#id_address_owner').style.color = "#ffffff";
                document.querySelector('#id_address_owner').style.border = '#ffffff';
                document.querySelector('#id_address_owner').tabIndex = "-1";

            })
        </script>
    </body>
</html>

agroshop/shop/templates/shop/createshop.html
{% extends 'shop/shopCreatingLayout.html' %}

{% block title %}Create Shop | AgroShop{% endblock %}

{% block body%}
<div id="shopdetails">
    <img src="../../static/createShop.jpeg" alt="" width="85%">
    <div id="shopdetailsform">
        <h3>Create your shop name</h3>
        <p style="font-size:14px; color: rgb(128, 126, 126);">You can use your brand's name or another name. A good shop name represents you and your products. You can change your shop name at any time.
            <a href="https://www.youtube.com/watch?v=y41nwoG8em8&feature=youtu.be" target="_blank">Learn more</a>
        </p>
        <form action="{% url 'setupshop' %}" method="POST">
             {%csrf_token%}
            <div class="form-group" style="text-align: left;">
                <label class="form-control container" for="customShopName">Shop name</label>
                <input id="shopname" type="text" class="form-control" placeholder="Add shop name here" name="customShopName" required>
                
                <!--checkbox-->
                <label class="checkbox-inline" style="margin-top: 7px;">
                    <input onclick="unlockBtn()" id="cbox" type="checkbox" required>
                    I understand that I am creating a new Google Account with its own settings.
                    <a href="https://safety.google/">Learn more</a>
                </label>
                <!--checkbox ends-->

            </div>
            <a href="{% url 'homepage' %}"><button class="btn btn-light" style="color: blue; background-color:white">CANCEL</button></a>
            <button class="btn btn-light" style="color: white; background-color:#008CBA" type="submit" id="createbtn">CREATE</button>
        </form>   
        <br>
    </div>
    <div style="padding: 18px 80px 0 80px;">
        <p><small>You can view your Google Account at anytime by just logging into <a href="https://myaccounts.google.com">myaccount.google.com</a><br>Learn more about channels and brand accounts. By selecting 'Create' you agree to<br><a href="">AgroShop's Terms of Service.</a></small></p>

        <small>&copy; 2022 Google</small>
    </div>
</div>
{%endblock%}

agroshop/shop/templates/shop/displaymap.html
{% extends 'shop/layout.html'%}

{% block title %}Get directions | AgroShop{% endblock %}

{%block body%}
<div id="directions" class="profiledivisions" style="padding: 80px; margin-left: 0px; text-align: center; background-color: rgb(241, 240, 240);;">
    <h3>We are waiting for you... Reach us using the following map.</h3>
    <br>
    <iframe src="{{shop.maplink}}" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
    referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
{%endblock%}

agroshop/shop/templates/shop/error.html
<html>
    <head>
        <title>error! | AgroShop</title>
        <!--Favicon-->
        <link rel="icon" href="../../static/Bag_favicon.jpg" type="image/x-icon">
    </head>
    <body>
        <h3>{{message}}</h3>
        redirecting you back, {{info}}
        <script>
            // sleep time expects milliseconds
            function sleepNow (time) {
                return new Promise((resolve) => setTimeout(resolve, time));
            }
            // Usage!
            sleepNow(2500).then(() => {
                // Do something after the sleep!
            window.history.back();
            });
        </script>
    </body>
</html>

agroshop/shop/templates/shop/locationresults.html
{% extends "shop/layout.html"%}

{%block title%}Shops around you - AgroShop{%endblock%}

{%block body%}
        {% if shops %}
        <div class="shadow mb-5 rounded" style="padding: 3px 3px 3px 9%; background-color: #f7f8f9;">
        {%else%}
        <div class="shadow mb-5 rounded" style="padding: 3px 3px 3px 3px; background-color: #f7f8f9;">
        {%endif%}
        {% for shop in shops %}
        
            <div class="profileproducts shadow p-3 bg-white rounded" style="margin: 10px; height: 265px; width: 272px;">
                <a href="" style="color:black; text-decoration:none;">
                    <img style="margin-bottom: 4px; max-height:112.6px" src="{{shop.coverpic.url}}" alt="" width="98%" height="120px"><br>
                    
                    <img src="{{shop.shoppicture.url}}" alt="NoVideos" style="width: 40px; border-radius: 50%; margin: 5px 0px 0px 5px;">
                    <b style="display: inline-block; width: 170px;">{{shop.shopname}}</b>
                    <small style="display: inline-block; width: 200px;  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;margin-left: 5px;">{{shop.description}}</small>
                    <a href="{% url 'displaymap' shop.id %}"><button class="btn btn-info" style="margin-top: 10px;">Get Directions</button></a>
                    <a href="{% url 'viewshop' shop.id %}"><button class="btn btn-success"style="margin-top: 10px;">View Shop</button></a>
                </a>
            </div>
            
            
        {%empty%}
            <div class="cartdivs" style="width: 100%; text-align: center; background-color: #f7f8f9; padding-top: 50px;">
                <img id="emptycartimg" src="../../static/shopnotfound1.png" alt="">
                <h5>OOPS!</h5>
                <p style="">Looks like there are no agro shops around you.<br>We are trying to start shops around you.</p>
                <a href="{% url 'homepage' %}" style="display:inline-block; margin-bottom: 150px;"><button class="btn btn-success">Explore others</button></a>
            </div>
        {%endfor%}
    </div>
{%endblock%}